# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: UC Davis Design Career Fair 2016
email: ucddesigncareerfair@gmail.com
description: "The 2nd Annual UC Davis Design Career Fair aims to empower students to take risks not only in their designs, but also career aspirations. By providing students career resources we hope to bridge our talented designers to esteemed companies."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ucddesigncareerfair.com" # the base hostname & protocol for your site

sass:
  style: compressed

# Build settings
markdown: kramdown